/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
    reportsSidebar: [{type: 'autogenerated', dirName: 'reports'}],
};

module.exports = sidebars;
