"""Domain models for SOAR Lab.

This module contains the core domain entities as dataclasses,
providing type safety and enforcing business invariants.
Using dataclasses instead of Pydantic to avoid framework coupling
in the domain layer.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import List, Optional, Dict, Any


class AlertSeverity(Enum):
    """Alert severity levels."""
    LOW = 1
    MEDIUM = 2
    HIGH = 3
    CRITICAL = 4


class AlertStatus(Enum):
    """Alert status values."""
    NEW = "new"
    IN_PROGRESS = "in_progress"
    RESOLVED = "resolved"
    CLOSED = "closed"


@dataclass
class IOC:
    """Indicator of Compromise.

    Represents a threat indicator with its type and value.
    """
    ioc_type: str  # e.g., "hash", "ip", "domain", "url"
    value: str
    description: Optional[str] = None
    source: Optional[str] = None
    confidence: float = 1.0  # 0.0 to 1.0
    tags: List[str] = field(default_factory=list)

    def __post_init__(self):
        """Validate IOC invariants."""
        if not self.ioc_type:
            raise ValueError("IOC type is required")
        if not self.value:
            raise ValueError("IOC value is required")
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError("Confidence must be between 0.0 and 1.0")


@dataclass
class Alert:
    """Security alert entity.

    Represents a security alert generated by the SIEM or other sources.
    """
    alert_id: str
    hostname: str
    src_ip: str
    severity: AlertSeverity
    event_type: str
    description: str
    process_name: Optional[str] = None
    hash: Optional[str] = None
    mitre_techniques: List[str] = field(default_factory=list)
    status: AlertStatus = AlertStatus.NEW
    timestamp: datetime = field(default_factory=lambda: datetime.utcnow())
    iocs: List[IOC] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        """Validate alert invariants."""
        if not self.alert_id:
            raise ValueError("Alert ID is required")
        if not self.hostname:
            raise ValueError("Hostname is required")
        if not self.src_ip:
            raise ValueError("Source IP is required")

    def add_ioc(self, ioc: IOC) -> None:
        """Add an IOC to the alert."""
        self.iocs.append(ioc)

    def get_critical_iocs(self) -> List[IOC]:
        """Get IOCs with high confidence."""
        return [ioc for ioc in self.iocs if ioc.confidence >= 0.8]

    def to_dict(self) -> Dict[str, Any]:
        """Convert alert to dictionary for serialization."""
        return {
            "alert_id": self.alert_id,
            "hostname": self.hostname,
            "src_ip": self.src_ip,
            "severity": self.severity.value,
            "event_type": self.event_type,
            "description": self.description,
            "process_name": self.process_name,
            "hash": self.hash,
            "mitre_techniques": self.mitre_techniques,
            "status": self.status.value,
            "timestamp": self.timestamp.isoformat(),
            "iocs": [self._ioc_to_dict(ioc) for ioc in self.iocs],
            "metadata": self.metadata,
        }

    @staticmethod
    def _ioc_to_dict(ioc: IOC) -> Dict[str, Any]:
        """Convert IOC to dictionary."""
        return {
            "ioc_type": ioc.ioc_type,
            "value": ioc.value,
            "description": ioc.description,
            "source": ioc.source,
            "confidence": ioc.confidence,
            "tags": ioc.tags,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Alert":
        """Create Alert from dictionary."""
        severity = AlertSeverity(data.get("severity", 2))
        status = AlertStatus(data.get("status", "new"))
        iocs = [IOC(**ioc) for ioc in data.get("iocs", [])]

        return cls(
            alert_id=data["alert_id"],
            hostname=data["hostname"],
            src_ip=data["src_ip"],
            severity=severity,
            event_type=data["event_type"],
            description=data["description"],
            process_name=data.get("process_name"),
            hash=data.get("hash"),
            mitre_techniques=data.get("mitre_techniques", []),
            status=status,
            timestamp=datetime.fromisoformat(data.get("timestamp", datetime.utcnow().isoformat())),
            iocs=iocs,
            metadata=data.get("metadata", {}),
        )


@dataclass
class Case:
    """Incident case entity.

    Represents a security incident case managed in TheHive or similar systems.
    """
    case_id: str
    title: str
    description: str
    severity: AlertSeverity
    status: AlertStatus = AlertStatus.NEW
    tags: List[str] = field(default_factory=list)
    tlp: int = 2  # Traffic Light Protocol level
    created_at: datetime = field(default_factory=lambda: datetime.utcnow())
    updated_at: Optional[datetime] = None
    assigned_to: Optional[str] = None
    alerts: List[str] = field(default_factory=list)  # Alert IDs
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        """Validate case invariants."""
        if not self.case_id:
            raise ValueError("Case ID is required")
        if not self.title:
            raise ValueError("Title is required")
        if not 0 <= self.tlp <= 4:
            raise ValueError("TLP must be between 0 and 4")

    def add_alert(self, alert_id: str) -> None:
        """Add an alert ID to the case."""
        if alert_id not in self.alerts:
            self.alerts.append(alert_id)

    def update_status(self, new_status: AlertStatus) -> None:
        """Update case status."""
        self.status = new_status
        self.updated_at = datetime.utcnow()

    def to_dict(self) -> Dict[str, Any]:
        """Convert case to dictionary for serialization."""
        return {
            "case_id": self.case_id,
            "title": self.title,
            "description": self.description,
            "severity": self.severity.value,
            "status": self.status.value,
            "tags": self.tags,
            "tlp": self.tlp,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
            "assigned_to": self.assigned_to,
            "alerts": self.alerts,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Case":
        """Create Case from dictionary."""
        severity = AlertSeverity(data.get("severity", 2))
        status = AlertStatus(data.get("status", "new"))
        updated_at = datetime.fromisoformat(data["updated_at"]) if data.get("updated_at") else None

        return cls(
            case_id=data["case_id"],
            title=data["title"],
            description=data["description"],
            severity=severity,
            status=status,
            tags=data.get("tags", []),
            tlp=data.get("tlp", 2),
            created_at=datetime.fromisoformat(data.get("created_at", datetime.utcnow().isoformat())),
            updated_at=updated_at,
            assigned_to=data.get("assigned_to"),
            alerts=data.get("alerts", []),
            metadata=data.get("metadata", {}),
        )
