
# /etc/cortex/application.conf

## Elasticsearch / OpenSearch
search {
  # Índice donde Cortex guarda sus datos
  index = cortex

  # URI del clúster (OpenSearch/Elasticsearch)
  uri = "http://opensearch:9200"
}

## Cacheo de resultados de analyzers
cache {
  job = 10 minutes
  # (user y organization tienen por defecto 5 minutos)
}

## Selección de "job runners"
# Desactiva Kubernetes y usa Docker y proceso local
job {
  runner = [ docker, process ]
}

## Catálogos oficiales de analyzers y responders (modo Docker)
analyzer {
  urls = [ "https://download.thehive-project.org/analyzers.json" ]
}
responder {
  urls = [ "https://download.thehive-project.org/responders.json" ]
}
