
# Cortex 3.x configuration (HOCON)
# Secret: define uno en producción
#play.http.secret.key = "***CHANGEME***"

# ElasticSearch
search {
  index = cortex
  uri = "http://elasticsearch:9200"
}

# Cache de jobs (opcional)
cache.job = 10 minutes

# Escucha
http.port = 9001

# Directorio de trabajos (persistente via volumen)
job-directory = "/var/lib/cortex"
