
version: "3.9"

networks:
  soar_net:
    driver: bridge

volumes:
  pgdata:
  thehive_data:
  cortex_data:
  shuffle_data:

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [soar_net]

  redis:
    image: redis:6
    networks: [soar_net]

  thehive:
    image: thehiveproject/thehive:latest
    depends_on: [postgres]
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USER=${POSTGRES_USER}
    ports:
      - "9000:9000"
    networks: [soar_net]
    volumes:
      - thehive_data:/opt/thehive/data

  cortex:
    image: thehiveproject/cortex:latest
    depends_on: [redis]
    ports:
      - "9001:9001"
    networks: [soar_net]
    volumes:
      - cortex_data:/var/lib/cortex

  shuffle:
    image: frikky/shuffle:latest
    depends_on: [redis]
    ports:
      - "3000:3000"
    networks: [soar_net]
    volumes:
      - shuffle_data:/shuffle-app-data
