#!/usr/bin/env python3
"""Restores SOAR service credentials after a make up.

This script reads the JSON file generated by preserve_credentials.py and
restores the credentials in the corresponding services.

Usage:
    python restore_credentials.py
"""

import base64
import json
import logging
import os
import re
from pathlib import Path

import requests

from soar_lab.common.constants import (
    AUTH_BASIC_PREFIX,
    AUTH_BEARER_PREFIX,
    CONTENT_TYPE_JSON,
    HEADER_AUTHORIZATION,
    HEADER_CONTENT_TYPE,
)

logger = logging.getLogger(__name__)

# Load environment variables
try:
    from dotenv import load_dotenv

    load_dotenv(".env.full", override=False)
except ImportError:
    pass

# Configuration
# Search on the host so it survives the reset
CREDENTIALS_FILE_HOST = Path("reports/validation/results/credentials_backup.json")
CREDENTIALS_FILE = Path("/app/reports/validation/results/credentials_backup.json")

# Service URLs
THEHIVE_URL = os.environ.get("THEHIVE_URL", "http://thehive:9000")
CORTEX_URL = os.environ.get("CORTEX_URL", "http://cortex:9001")
GRAFANA_URL = os.environ.get("GRAFANA_URL", "http://grafana:3000")

# Credentials for reconfiguration
THEHIVE_ADMIN_USER = os.environ.get("THEHIVE_ADMIN_USER", "admin")
THEHIVE_ADMIN_PASS = os.environ.get("THEHIVE_ADMIN_PASSWORD", "")
CORTEX_ADMIN_USER = os.environ.get("CORTEX_ADMIN_USER", "admin")
CORTEX_ADMIN_PASS = os.environ.get("CORTEX_ADMIN_PASSWORD", "")

if not THEHIVE_ADMIN_PASS:
    logger.warning("[WARN] Missing THEHIVE_ADMIN_PASSWORD; it will be regenerated during setup")
if not CORTEX_ADMIN_PASS:
    logger.warning("[WARN] Missing CORTEX_ADMIN_PASSWORD; it will be regenerated during setup")


def load_credentials():
    """Load preserved credentials."""
    # Try to load from the container first
    if CREDENTIALS_FILE.exists():
        with open(CREDENTIALS_FILE) as f:
            return json.load(f)

    # Try to load from the host
    if CREDENTIALS_FILE_HOST.exists():
        with open(CREDENTIALS_FILE_HOST) as f:
            return json.load(f)

    logger.warning("[WARN] Preserved credentials file not found")
    logger.warning(f"  Looking in: {CREDENTIALS_FILE}")
    logger.warning(f"  Looking in: {CREDENTIALS_FILE_HOST}")
    return None


def _get_current_thehive_key():
    """Read the current THEHIVE_API_KEY from .env.full."""
    for env_file in [Path(".env.full"), Path("/app/.env.full")]:
        if env_file.exists():
            content = env_file.read_text()
            m = re.search(r"^THEHIVE_API_KEY=(.+)$", content, re.MULTILINE)
            if m:
                return m.group(1).strip(), env_file
    return None, None


def _validate_thehive_key(key):
    """Return True if the key is accepted by TheHive."""
    try:
        r = requests.get(
            f"{THEHIVE_URL}/api/user/admin",
            headers={HEADER_AUTHORIZATION: f"{AUTH_BEARER_PREFIX} {key}"},
            timeout=10,
        )
        return r.ok
    except Exception:
        return False


def restore_thehive_credentials(api_key):
    """Restore TheHive API key by updating .env.full.

    If .env.full already has a valid key, keep it so as not to
    invalidate workflows created later.
    """
    current_key, env_file = _get_current_thehive_key()
    if current_key and _validate_thehive_key(current_key):
        logger.info("[OK] TheHive API key currently in .env.full is valid, keeping it")
        # If the backup does not match, we still write the current valid one
        api_key = current_key
    else:
        if not api_key:
            logger.info("[SKIP] TheHive API key not preserved and no valid key in .env.full")
            return False

        # Verify if the preserved key is valid
        if _validate_thehive_key(api_key):
            logger.info("[OK] TheHive API key preserved still valid")
        else:
            logger.warning("[WARN] TheHive API key preserved is invalid, generating new...")
            # Generate new key
            auth = base64.b64encode(f"{THEHIVE_ADMIN_USER}:{THEHIVE_ADMIN_PASS}".encode()).decode()
            r = requests.post(
                f"{THEHIVE_URL}/api/user/{THEHIVE_ADMIN_USER}/key/renew",
                data="{}",
                headers={
                    HEADER_AUTHORIZATION: f"{AUTH_BASIC_PREFIX} {auth}",
                    HEADER_CONTENT_TYPE: CONTENT_TYPE_JSON,
                },
                timeout=10,
            )
            if r.ok:
                api_key = r.text.strip().strip('"')
                logger.info("[OK] New TheHive API key generated")
            else:
                logger.error(
                    f"[ERROR] Could not generate new TheHive API key: HTTP {r.status_code}"
                )
                return False

    # Update .env.full
    try:
        env_file = Path(".env.full")
        if not env_file.exists():
            env_file = Path("/app/.env.full")

        if env_file.exists():
            content = env_file.read_text()
            import re

            if re.search(r"^THEHIVE_API_KEY=", content, re.MULTILINE):
                content = re.sub(
                    r"^THEHIVE_API_KEY=.*$",
                    f"THEHIVE_API_KEY={api_key}",
                    content,
                    flags=re.MULTILINE,
                )
            else:
                content += f"\nTHEHIVE_API_KEY={api_key}"
            env_file.write_text(content)
            logger.info("[OK] THEHIVE_API_KEY updated in .env.full")
            return True
        else:
            logger.warning("[WARN] .env.full not found to update")
            return False
    except Exception as e:
        logger.error(f"[ERROR] Error updating .env.full: {e}")
        return False


def restore_cortex_credentials(api_key):
    """Restore Cortex API key by updating .env.full."""
    if not api_key:
        logger.info("[SKIP] Cortex API key not preserved")
        return False

    # Cortex API key is regenerated automatically on make up
    # We only verify it exists
    logger.info(f"[INFO] Cortex API key preserved: {api_key[:8]}...")
    logger.info("[INFO] Cortex API key is regenerated automatically on make up")

    # Update .env.full with the preserved key
    try:
        env_file = Path(".env.full")
        if not env_file.exists():
            env_file = Path("/app/.env.full")

        if env_file.exists():
            content = env_file.read_text()
            import re

            if re.search(r"^CORTEX_API_KEY=", content, re.MULTILINE):
                content = re.sub(
                    r"^CORTEX_API_KEY=.*$", f"CORTEX_API_KEY={api_key}", content, flags=re.MULTILINE
                )
            else:
                content += f"\nCORTEX_API_KEY={api_key}"
            env_file.write_text(content)
            logger.info("[OK] CORTEX_API_KEY updated in .env.full")
            return True
        else:
            logger.warning("[WARN] .env.full not found to update")
            return False
    except Exception as e:
        logger.error(f"[ERROR] Error updating .env.full: {e}")
        return False


def restore_shuffle_credentials(api_key):
    """Restore the Shuffle API key."""
    if not api_key:
        logger.info("[SKIP] Shuffle API key not preserved")
        return False

    # Shuffle API key is generated on each fresh deploy
    # It makes no sense to restore it, we just inform
    logger.info(f"[INFO] Shuffle API key preserved: {api_key[:8]}...")
    logger.info("[INFO] Shuffle API key is generated automatically on fresh deploy")
    return True


def restore_grafana_credentials(grafana_creds):
    """Restore the Grafana credentials."""
    if not grafana_creds:
        logger.info("[SKIP] Grafana credentials not preserved")
        return False

    user = grafana_creds.get("user", "admin")
    password = grafana_creds.get("password", os.environ.get("GRAFANA_ADMIN_PASSWORD", ""))

    logger.info(f"[INFO] Grafana credentials preserved: {user} / {password[:4]}...")
    logger.info("[INFO] Grafana uses static credentials, no restoration required")
    return True


def main():
    """Main function."""
    print("=" * 60)
    print("RESTORING SOAR SERVICE CREDENTIALS")
    print("=" * 60)

    credentials = load_credentials()
    if not credentials:
        logger.warning("[WARN] Could not load preserved credentials; continuing with initial setup")
        print("=" * 60)
        print("RESTORATION COMPLETED (without previous credentials)")
        print("=" * 60)
        return

    logger.info(f"[INFO] Credentials preserved on: {credentials.get('timestamp', 'unknown')}")
    print()

    # Restore each service
    results = {
        "thehive": restore_thehive_credentials(credentials.get("thehive_api_key")),
        "cortex": restore_cortex_credentials(credentials.get("cortex_api_key")),
        "shuffle": restore_shuffle_credentials(credentials.get("shuffle_api_key")),
        "grafana": restore_grafana_credentials(credentials.get("grafana")),
    }

    print()
    print("=" * 60)
    print("RESTORATION RESULT")
    print("=" * 60)
    for service, success in results.items():
        status = "✅ OK" if success else "❌ FAIL"
        print(f"  {service}: {status}")

    print("=" * 60)
    print("RESTORATION COMPLETED")
    print("=" * 60)


if __name__ == "__main__":
    main()
