#!/usr/bin/env python3
"""Verify Docker image digests for all services defined in .env.

This script resolves the digest (sha256) of each image referenced in the
environment files without pulling the image.  It can optionally generate
a ``requirements-docker.lock`` file with image@sha256 references for
fully reproducible deployments.

Usage:
    python scripts/maintenance/verify_image_digests.py          # verify only
    python scripts/maintenance/verify_image_digests.py --write   # generate lock file
"""

import argparse
import subprocess
import sys
from pathlib import Path

# Images to verify (variable name -> default image)
IMAGES = [
    "MISP_DB_IMAGE",
    "SHUFFLE_FRONTEND_IMAGE",
    "SHUFFLE_BACKEND_IMAGE",
    "ORBORUS_IMAGE",
    "REDIS_IMAGE",
    "THEHIVE_IMAGE",
    "TENZIR_IMAGE",
    "NGINX_IMAGE",
    "ELASTICSEARCH_IMAGE",
    "OPENSEARCH_IMAGE",
    "OPENSEARCH_DASHBOARDS_IMAGE",
    "MISP_CORE_IMAGE",
    "MISP_MODULES_IMAGE",
    "POSTGRES_IMAGE",
    "GRAFANA_IMAGE",
    "LOKI_IMAGE",
    "PROMTAIL_IMAGE",
]


def load_env(env_path: Path) -> dict[str, str]:
    """Load environment variables from a .env file."""
    env = {}
    if not env_path.exists():
        return env
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, value = line.split("=", 1)
            env[key.strip()] = value.strip()
    return env


def get_digest(image: str) -> str | None:
    """Get the sha256 digest of an image without pulling it."""
    try:
        result = subprocess.run(
            [
                "docker", "buildx", "imagetools", "inspect",
                image, "--format", "{{.Manifest.Digest}}",
            ],
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except Exception as e:
        print(f"  ERROR: {e}", file=sys.stderr)
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description="Verify Docker image digests")
    parser.add_argument(
        "--env-file",
        default=".env",
        help="Path to .env file (default: .env)",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="Write a requirements-docker.lock file with image@sha256 references",
    )
    args = parser.parse_args()

    env_path = Path(args.env_file)
    if not env_path.exists():
        # Try .env.example as fallback
        env_path = Path(".env.example")
    env = load_env(env_path)

    print(f"Verifying {len(IMAGES)} Docker images from {env_path}...")
    print()

    results: list[tuple[str, str, str | None]] = []
    for var_name in IMAGES:
        image = env.get(var_name, "")
        if not image:
            print(f"  {var_name}: NOT SET")
            results.append((var_name, "", None))
            continue
        digest = get_digest(image)
        if digest:
            print(f"  {var_name}: {image} -> {digest[:19]}...")
            results.append((var_name, image, digest))
        else:
            print(f"  {var_name}: {image} -> FAILED")
            results.append((var_name, image, None))

    # Summary
    ok = sum(1 for _, _, d in results if d)
    failed = len(results) - ok
    print()
    print(f"Results: {ok} verified, {failed} failed")

    if args.write:
        lock_path = Path("requirements-docker.lock")
        with open(lock_path, "w", encoding="utf-8") as f:
            f.write("# Docker image digests — generated by verify_image_digests.py\n")
            f.write("# Use these image@sha256 references for fully reproducible deployments.\n")
            f.write(
                "# Regenerate with: python scripts/maintenance/"
                "verify_image_digests.py --write\n\n"
            )
            for var_name, image, digest in results:
                if digest:
                    f.write(f"{var_name}={image}@{digest}\n")
                else:
                    f.write(f"{var_name}={image}\n")
        print(f"Written: {lock_path}")

    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
