---
- hosts: soar
  become: yes
  tasks:
    - name: Create base directories
      file:
        path: "/opt/soar-lab/{{ item }}"
        state: directory
        owner: vagrant
        group: vagrant
        mode: "0755"
      loop:
        - docker
        - data

    - name: Copy docker-compose skeleton
      copy:
        src: ../docker/docker-compose.yml
        dest: /opt/soar-lab/docker/docker-compose.yml
        owner: vagrant
        group: vagrant
        mode: "0644"
