"""Canonical Shuffle webhook URL resolver.

The single source of truth for the active Shuffle webhook is
``reports/validation/results/webhook_info.json`` generated by
``init_shuffle_webhook.py``. Environment variables can override it.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

from soar_lab.common.constants import SHUFFLE_WEBHOOK_TEMPLATE, WEBHOOK_INFO_PATHS
from soar_lab.common.runtime import is_inside_container
from soar_lab.config.logging import get_logger

__all__ = ["resolve_webhook_url"]

logger = get_logger(__name__)


def resolve_webhook_url(
    base_dir: Path | None = None,
    env_url: str | None = None,
    token: str | None = None,
) -> str | None:
    """Resolve the Shuffle webhook URL from env, token or webhook_info.json.

    The resolution order is as follows.
      1. ``env_url`` or ``SHUFFLE_WEBHOOK_URL``.
      2. ``token`` or ``SIEM_WEBHOOK_TOKEN`` (builds backend URL).
      3. ``webhook_info.json`` generated by ``init_shuffle_webhook.py``.
         Inside a container prefers the internal ``webhook_url``; otherwise
         prefers the host ``webhook_url_host``.

    Args:
        base_dir: Project base directory to search for ``webhook_info.json``.
        env_url: Explicit webhook URL override (highest priority).
        token: Shuffle webhook token used to build the backend URL.

    Returns:
        str: Resolved webhook URL, or None if no source is available.
    """
    if env_url:
        return env_url

    env_url = os.environ.get("SHUFFLE_WEBHOOK_URL")
    if env_url:
        return env_url

    env_token = token or os.environ.get("SIEM_WEBHOOK_TOKEN")
    if env_token:
        return SHUFFLE_WEBHOOK_TEMPLATE.format(token=env_token)

    candidates: list[Path] = []
    if base_dir:
        candidates.append(base_dir / "reports" / "validation" / "results" / "webhook_info.json")
        candidates.append(base_dir / "webhook_info.json")
    candidates.extend(Path(p) for p in WEBHOOK_INFO_PATHS)

    for path in candidates:
        if not path.exists():
            continue
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            if is_inside_container():
                url = data.get("webhook_url") or data.get("webhook_url_host")
            else:
                url = data.get("webhook_url_host") or data.get("webhook_url")
            if url:
                return str(url)
        except Exception as exc:
            logger.warning("Could not read webhook info from %s: %s", path, exc)

    return None
