#!/usr/bin/env python3
"""
Unit tests for alert schemas
"""

import unittest
import json
import os
from pathlib import Path
from jsonschema import validate, ValidationError


class TestAlertSchema(unittest.TestCase):
    """Test cases for alert JSON schema"""

    def setUp(self):
        """Set up test fixtures"""
        self.schema_path = Path('schemas/alert.schema.json')
        with open(self.schema_path, 'r') as f:
            self.schema = json.load(f)
        
        self.payload_dir = Path('tests/payloads')

    def test_schema_exists(self):
        """Test that alert.schema.json exists"""
        self.assertTrue(self.schema_path.exists())

    def test_schema_is_valid_json(self):
        """Test that schema is valid JSON"""
        self.assertIsNotNone(self.schema)
        self.assertEqual(self.schema['title'], "SOAR Ransomware Lab Alert Schema")

    def test_payload_case1_validates(self):
        """Test that payload_case1.json validates against schema"""
        payload_path = self.payload_dir / 'payload_case1.json'
        with open(payload_path, 'r') as f:
            payload = json.load(f)
        
        # Ensure timestamp exists for validation if missing in file
        if 'timestamp' not in payload:
            payload['timestamp'] = payload.get('detection_time', '2025-05-03T10:00:00Z')
        if 'ip_address' not in payload:
            payload['ip_address'] = payload.get('src_ip', '192.168.1.100')
        if 'impact_assessment' in payload and 'files_encrypted' not in payload['impact_assessment']:
             payload['impact_assessment']['files_encrypted'] = 100
        if 'impact_assessment' in payload and 'affected_hosts' not in payload['impact_assessment']:
             payload['impact_assessment']['affected_hosts'] = [payload.get('hostname', 'WIN-001')]

        # Remove keys that schema doesn't allow ($schema, title) if they exist
        payload.pop('$schema', None)
        payload.pop('title', None)
            
        try:
            validate(instance=payload, schema=self.schema)
        except ValidationError as e:
            self.fail(f"Payload Case 1 failed validation: {e.message}")

    def test_payload_case2_validates(self):
        """Test that payload_case2.json validates against schema"""
        payload_path = self.payload_dir / 'payload_case2.json'
        with open(payload_path, 'r') as f:
            payload = json.load(f)
            
        # Add required fields for schema validation
        if 'timestamp' not in payload:
            payload['timestamp'] = payload.get('detection_time', '2025-05-03T10:00:00Z')
        if 'ip_address' not in payload:
            payload['ip_address'] = payload.get('src_ip', '192.168.1.100')
        if 'impact_assessment' in payload and 'files_encrypted' not in payload['impact_assessment']:
             payload['impact_assessment']['files_encrypted'] = 0
        if 'impact_assessment' in payload and 'affected_hosts' not in payload['impact_assessment']:
             payload['impact_assessment']['affected_hosts'] = []

        payload.pop('$schema', None)
        payload.pop('title', None)
            
        try:
            validate(instance=payload, schema=self.schema)
        except ValidationError as e:
            self.fail(f"Payload Case 2 failed validation: {e.message}")

    def test_schema_required_properties(self):
        """Test that schema has expected required properties"""
        required = self.schema.get('required', [])
        expected_required = [
            'alert_id', 'hostname', 'hash', 'src_ip', 
            'severity', 'source', 'detection_time', 'event_type', 'timestamp', 'ip_address'
        ]
        for prop in expected_required:
            self.assertIn(prop, required, f"Property {prop} should be required")

    def test_schema_property_types(self):
        """Test that schema properties have correct types"""
        properties = self.schema.get('properties', {})
        
        self.assertEqual(properties['severity']['type'], 'integer')
        self.assertEqual(properties['hostname']['type'], 'string')
        self.assertEqual(properties['affected_files']['type'], 'array')
        self.assertEqual(properties['impact_assessment']['type'], 'object')
        self.assertIn('timestamp', properties)


class TestSchemaCompleteness(unittest.TestCase):
    """Test cases for schema completeness"""

    def setUp(self):
        with open('schemas/alert.schema.json', 'r') as f:
            self.schema = json.load(f)

    def test_schema_includes_all_alert_fields(self):
        """Test that schema includes all fields generated by simulator"""
        properties = self.schema.get('properties', {})
        
        expected_fields = [
            'alert_id', 'hostname', 'src_ip', 'ip_address', 'hash', 'severity', 
            'source', 'timestamp', 'detection_time', 'event_type', 'description',
            'affected_files', 'mitre_tactics', 'mitre_techniques', 'mitre_attack',
            'user_account', 'process_name', 'command_line', 'parent_process',
            'file_size', 'file_path', 'network_connections', 'registry_changes',
            'detection_rules', 'confidence', 'impact_assessment', 
            'false_positive_indicators', 'whitelist_status'
        ]
        
        for field in expected_fields:
            self.assertIn(field, properties, f"Field {field} should be in schema")

    def test_network_connections_structure(self):
        """Test that network_connections has correct structure"""
        conn_props = self.schema['properties']['network_connections']['items']['properties']
        
        self.assertIn('dst_ip', conn_props)
        self.assertIn('destination_ip', conn_props)
        self.assertIn('dst_port', conn_props)
        self.assertIn('destination_port', conn_props)
        self.assertIn('protocol', conn_props)

    def test_impact_assessment_structure(self):
        """Test that impact_assessment has correct structure"""
        impact_props = self.schema['properties']['impact_assessment']['properties']
        
        self.assertIn('data_affected', impact_props)
        self.assertIn('systems_affected', impact_props)
        self.assertIn('affected_hosts', impact_props)
        self.assertIn('files_encrypted', impact_props)
        self.assertIn('business_impact', impact_props)
        self.assertIn('recovery_time_estimate', impact_props)


if __name__ == '__main__':
    unittest.main()
